### ISSUE TITLE
Bug: Cannot run ./ela-wallet -l

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.ELA.Client#39]
```bash
kpachhai@kpxubuntu:~/dev/src/github.com/elastos/Elastos.ELA.Client$ ./ela-cli wallet -l
panic: interface conversion: interface {} is string, not float64

goroutine 1 [running]:
github.com/elastos/Elastos.ELA.Client/rpc.GetChainHeight(0x81e8c0, 0xc42000c0c0, 0x822a40)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/rpc/json_rpc.go:36 +0xc9
github.com/elastos/Elastos.ELA.Client/wallet.(*DataSyncImpl).needSyncBlocks(0xc4200815f0, 0xc42000e020, 0x1)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/wallet/data_sync.go:67 +0x26
github.com/elastos/Elastos.ELA.Client/wallet.(*DataSyncImpl).SyncChainData(0xc4200815f0)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/wallet/data_sync.go:39 +0x45b
github.com/elastos/Elastos.ELA.Client/wallet.(*DataStoreImpl).SyncChainData(0xc420101540)
	<autogenerated>:1 +0x3d
github.com/elastos/Elastos.ELA.Client/wallet.(*WalletImpl).SyncChainData(0xc42000c040)
	<autogenerated>:1 +0x3c
github.com/elastos/Elastos.ELA.Client/cli/wallet.listBalanceInfo(0xce0b40, 0xc42000c040, 0x4, 0x1)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/cli/wallet/wallet.go:103 +0x38
github.com/elastos/Elastos.ELA.Client/cli/wallet.walletAction(0xc4200d06e0)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/cli/wallet/wallet.go:228 +0xba1
github.com/elastos/Elastos.ELA.Client/vendor/github.com/urfave/cli.HandleAction(0x833140, 0x8d6650, 0xc4200d06e0, 0x0, 0xc4200a8c00)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/vendor/github.com/urfave/cli/app.go:504 +0x127
github.com/elastos/Elastos.ELA.Client/vendor/github.com/urfave/cli.Command.Run(0x8bd01d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8c0822, 0x11, 0x0, ...)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/vendor/github.com/urfave/cli/command.go:165 +0x4bb
github.com/elastos/Elastos.ELA.Client/vendor/github.com/urfave/cli.(*App).Run(0xc420134000, 0xc420080060, 0x3, 0x3, 0x0, 0x0)
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/vendor/github.com/urfave/cli/app.go:259 +0x740
main.main()
	/home/kpachhai/dev/src/github.com/elastos/Elastos.ELA.Client/ela-cli.go:40 +0x35d
```

**Comment by bocheng0000** [comment]
Please tell me the branch you build.

**Comment by kpachhai** [comment]
master
